server :
    port : 80
    
spring :
    mvc : 
        view :
            prefix : /views/
            suffix : .jsp

#        static-path-pattern : /resources/**

    servlet :
        multipart :
            max-file-size: 10MB 
            max-request-size: 10MB

    datasource :
        driver-class-name : com.mysql.jdbc.Driver
        url : jdbc:mysql://localhost:3306/green_db?allowMultiQueries=true
        username : green_mem
        password : 123456
        
mybatis :
    mapper-locations : mappers/**/*.xml
    type-aliases-package : aaa.model