server :
    port : 80
    
spring :
    mvc : 
        view :
            prefix : /views/
            suffix : .jsp

#        static-path-pattern : /resources/**

    servlet :
        multipart :
            max-file-size: 10MB #용량제한
            max-request-size: 10MB